<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>1.0.6-alpha</Version>
        <Copyright>All Rights Reserved!</Copyright>
        <PackageProjectUrl>https://www.botech.dev</PackageProjectUrl>
        <PackageIcon>BoTechLogoSmall.png</PackageIcon>
        <Authors>www.botech.dev</Authors>
        <AssemblyVersion>1.0.6.0</AssemblyVersion>
        <RepositoryUrl>https://github.com/BoTech-Development/BoTech.UI.Forms/</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Controls\Layout\Flyout\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BoTech.XmlParser" Version="1.1.0" />
    </ItemGroup>

    <ItemGroup>
      <None Update="BoTectLogoSmall.drawio.png">
        <Pack>True</Pack>
      </None>
    </ItemGroup>

</Project>
