<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <Title>BoTech.UI.Forms.Avalonia.Demo.Browser</Title>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" Version="12.1.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BoTech.UI.Forms.Avalonia.Demo\BoTech.UI.Forms.Avalonia.Demo.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="BoTectLogoSmall.drawio.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>
</Project>
