using BoTech.UI.Forms.Controls.Input;
using BoTech.UI.Forms.Rendering;

namespace BoTech.UI.Forms.Controls.Builder;
/// <summary>
/// This class can be used to build a standard layout for input controls.
/// </summary>
public interface IInputLayoutBuilder
{
    /// <summary>
    /// Builds a standard layout configuration for inputs, including a label, the input control itself, and a help description <see cref="IHelpDescriptionOfFormElement"/>.
    /// </summary>
    /// <typeparam name="T">the generic type of <see cref="IInput{T}"/></typeparam>
    /// <param name="innerComponents">The components to insert between the label and the help description</param>
    /// <param name="instanceOfControl">the instance of the input control. Must implement <see cref="IInput{T}"/></param>
    /// <returns>The instance of the <see cref="IHelpDescriptionOfFormElement"/> generated by this method and the new config.</returns>
    public (IComponentBuilderConfiguration, IHelpDescriptionOfFormElement) BuildStandardLayoutConfiguration<T>(List<IComponentBuilderConfiguration> innerComponents, IInput<T> instanceOfControl);
    /// <summary>
    /// Builds a standard layout configuration for inputs, including a label, the input control itself, and a help description <see cref="IHelpDescriptionOfFormElement"/>.
    /// </summary>
    /// <typeparam name="T">the generic type of <see cref="IInput{T}"/></typeparam>
    /// <param name="config">The component to insert between the label and the help description</param>
    /// <param name="instanceOfControl">the instance of the input control. Must implement <see cref="IInput{T}"/></param>
    /// <returns>The instance of the <see cref="IHelpDescriptionOfFormElement"/> generated by this method and the new config.</returns>
    public (IComponentBuilderConfiguration, IHelpDescriptionOfFormElement) BuildStandardLayoutConfiguration<T>(IComponentBuilderConfiguration config, IInput<T> instanceOfControl);
}